/* 
* Automatically generated by cra-envs.
* If you wish to declare a new environment variable declare it in the .env file (prefixed by REACT_APP_)
* then run 'npx generate-env-getter' at the root of your project.
* This file will be updated.
*/
import { getEnvVarValue } from "cra-envs";

export const envNames = [
    "OIDC_URL",
    "OIDC_REALM",
    "OIDC_CLIENT_ID",
    "OIDC_EMAIL_CLAIM",
    "OIDC_FAMILY_NAME_CLAIM",
    "OIDC_FIRST_NAME_CLAIM",
    "OIDC_USERNAME_CLAIM",
    "OIDC_GROUPS_CLAIM",
    "OIDC_LOCALE_CLAIM"
] as const;

export type EnvNames = typeof envNames[number];

let env: Record<EnvNames, string> | undefined = undefined;

export function getEnv() {

    if (env === undefined) {
        env = {} as Record<EnvNames, string>;
        for (const envName of envNames) {
            env[envName] = getEnvVarValue(envName);
        }
    }

    return env;

}
